# Generated by Django 6.0.6 on 2026-06-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaultifyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='You have entered no notes here'),
            preserve_default=False,
        ),
    ]
